name: Commitlint

on:
  pull_request:
    branches:
      - master

jobs:
  Commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js v14
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Enviroment setup
        run: npm ci
      - name: PR commits check
        run: npm run commitlint
