name: Pull Request Checks
on:
  pull_request:
    branches:
      - master
jobs:

  Conventional-Commits-Check:
    uses: AndreyProgr/estimate-js/.github/workflows/conventional-commits-check.yml@738b6b41618f09dc0eb74d1ff8cd4bab8960bd4f

  Continuous-Testing:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [15.x, 16.x, 17.x]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Enviroment setup
        run: |
          npm -v
          node -v
          echo "Triggered by a ${{ github.event_name }} event."
          echo "Running on a ${{ runner.os }} server."
          echo "Running from branch ${{ github.ref }} in ${{ github.repository }} repository."
          npm ci
          npm install -g stryker-cli
      - name: ESLint (static code analysis)
        run: npm run lint
      - name: Jest (unit testing)
        run: npm run test
      - name: Stryker Mutator (mutation testing)
        run: npm run stryker
      - name: Build
        run: npm run build
      - name: Size check
        run: npm run check-build-size
