name: Pull Request Checks
on:
  pull_request:
    branches:
      - master
jobs:

  Conventional-Commits-Check:
    uses: AndreyProgr/estimate-js/.github/workflows/conventional-commits-check.yml@738b6b41618f09dc0eb74d1ff8cd4bab8960bd4f

  Continuous-Testing:
    uses: AndreyProgr/estimate-js/.github/workflows/continuous-testing.yml@60d50648eabeec045dbd24d2133a59936e1e9536