name: Continuous Deployment
on:
  push:
    branches:
      - master
jobs:

  Continuous-Testing:
    uses: AndreyProgr/estimate-js/.github/workflows/continuous-testing.yml@60d50648eabeec045dbd24d2133a59936e1e9536

  Deployment:
    runs-on: ubuntu-latest
    needs: [Continuous-Testing]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Enviroment setup
        run: |
          npm -v
          node -v
          npm ci
      - name: Build
        run: npm run build
      - name: Release
        run: npm run release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
