name: Continuous Deployment
on:
  push:
    branches:
      - master
jobs:

  Continuous-Testing:
    uses: AndreyProgr/estimate-js/.github/workflows/continuous-testing.yml@60d50648eabeec045dbd24d2133a59936e1e9536

  Deployment:
    uses: AndreyProgr/estimate-js/.github/workflows/release.yml@b8a09c169d7f286ef48a31cc0dcb663b24e44c23
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
